### ISSUE TITLE
move mocha into the dependencies

### ISSUE THREAD

**Issue by seeden** [zordius/gulp-jsx-coverage#23]
hi I was not able to use your module until I added mocha into my dependencies
please move mocha from devDependencies into the dependencies

**Comment by zordius** [comment]
Yes, you need to add mocha into your dependency, the document already mentioned this: https://github.com/zordius/gulp-jsx-coverage#install . And I will not move mocha into dependencies because maybe someone like to use jasmine but not mocha, then my package will not waste disk space for him. :smile: Thank you for your suggestion!

**Comment by seeden** [comment]
Thank you for the explanation (I was blind). It makes sense :)
